require 'kramdown'
require 'capybara'

require 'dom_glancy/engine' if defined?(Rails)
require 'dom_glancy/dom_glancy'
require 'dom_glancy/version'
require 'dom_glancy/element'
require 'dom_glancy/analyzer'
require 'dom_glancy/file_name_builder'
require 'dom_glancy/svg'
require 'dom_glancy/configuration'
require 'dom_glancy/page_mapper'
require 'dom_glancy/map_file'
require 'dom_glancy/analysis_reporter'
require 'dom_glancy/change_anlyzer'
